"""
Execution Planner Schemas.
Defines the strict data contracts for the LLM planner.
"""

from pydantic import BaseModel, Field
from enum import Enum

class ToolName(str, Enum):
    """
    Strict enumeration of available enterprise tools.
    The planner is ONLY allowed to select from these exact values.
    """
    SUMMARY = "SUMMARY"
    RISK = "RISK"
    INSIGHTS = "INSIGHTS"
    ACTION_ITEMS = "ACTION_ITEMS"

class ExecutionStep(BaseModel):
    """
    Represents a single action the execution engine needs to take.
    """
    tool: ToolName = Field(
        ..., 
        description="The specific enterprise tool to execute."
    )
    reasoning: str = Field(
        ..., 
        description="Brief explanation of why this tool is selected for the user's query."
    )

class ExecutionPlan(BaseModel):
    """
    The complete multi-step plan generated by the LLM.
    """
    steps: list[ExecutionStep] = Field(
        ..., 
        description="The ordered sequence of tools to execute."
    )
    requires_multi_step: bool = Field(
        ...,
        description="True if the query requires multiple tools, False if a single tool suffices."
    )